name: kotlin
version: 0.8.0-DEV
schema: 1
scm: github.com/pubnub/kmp-chat
sdks:
  - 
      type: library
      full-name: JVM Chat SDK
      short-name: Chat
      artifacts:
        -
          language: kotlin
          tags:
            - Server
            - Mobile
          source-repository: https://github.com/pubnub/kmp-chat
          documentation: https://www.pubnub.com/docs/chat/kotlin-chat-sdk/overview
          tier: 2
          artifact-type: library
          distributions:
            -
              distribution-type: library
              distribution-repository: maven
              package-name: pubnub-chat-0.8.0-DEV
              location: https://repo.maven.apache.org/maven2/com/pubnub/pubnub-chat/0.8.0-DEV/pubnub-chat-0.8.0-DEV.jar
              supported-platforms:
                supported-operating-systems:
                  Android:
                    runtime-version:
                      - ART
                    target-api-level: 
                      - 23
                    minimum-api-level:
                      - 23
                    maximum-api-level:
                      - 30
                    target-architecture:
                      - armeabi-v7a
                      - atom
                      - armeabi
                      - arm64-v8a
                  Linux:
                    runtime-version:
                      - JVM 8 
                    minimum-os-version:
                      - Ubuntu 12.04
                    maximum-os-version:
                      - Ubuntu 20.04 LTS
                    target-architecture:
                      - x86
                      - x86-64
                  macOS:
                    runtime-version:
                      - JVM 8
                    minimum-os-version:
                      - macOS 10.12
                    maximum-os-version:
                      - macOS 11.0.1
                    target-architecture:
                      - x86-64
                  Windows:
                    runtime-version:
                      - JVM 8
                    minimum-os-version:
                      - Windows Vista Ultimate
                    maximum-os-version:
                      - Windows 10 Home
                    target-architecture:
                      - x86
                      - x86-64
              requires:
                -
                  name: retrofit
                  min-version: 2.9.0
                  location: https://repo.maven.apache.org/maven2/com/squareup/retrofit2/retrofit/2.9.0/retrofit-2.9.0.jar
                  license: Apache License, Version 2.0
                  license-url: https://github.com/square/retrofit/blob/2.9.0/LICENSE.txt
                  is-required: Required
                -
                  name: okhttp
                  min-version: 4.9.3
                  location: https://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/4.9.3/okhttp-4.9.3.jar
                  license: Apache License, Version 2.0
                  license-url: https://github.com/square/okhttp/blob/parent-3.14.9/LICENSE.txt
                  is-required: Required
                -
                  name: converter-gson
                  min-version: 2.9.0
                  location: https://repo.maven.apache.org/maven2/com/squareup/retrofit2/converter-gson/2.9.0/converter-gson-2.9.0.jar
                  license: Apache License, Version 2.0
                  license-url: https://github.com/square/retrofit/blob/2.9.0/LICENSE.txt
                  is-required: Required
                -
                  name: gson
                  min-version: 2.9.0
                  location: https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.9.0/gson-2.9.0.jar
                  license: Apache License, Version 2.0
                  license-url: https://github.com/google/gson/blob/gson-parent-2.8.6/LICENSE
                  is-required: Required
                -
                  name: json
                  min-version: "20231013"
                  location: https://repo.maven.apache.org/maven2/org/json/json/20231013/json-20231013.jar
                  license: Public Domain
                  license-url: https://github.com/stleary/JSON-java/blob/20210307/LICENSE
                  is-required: Required
                -
                  name: cbor
                  min-version: "0.9"
                  location: https://repo.maven.apache.org/maven2/co/nstant/in/cbor/0.9
                  license: The Apache Software License, Version 2.0
                  license-url: https://www.apache.org/licenses/LICENSE-2.0.txt
                  is-required: Required
changelog:
  - date: 2024-09-24
    version: v0.8.0
    changes:
      - type: feature
        text: "Blah blah."
  - date: 2024-06-26
    version: v0.8.0-DEV
    changes:
      - type: feature
        text: "Internal dev release."
supported-platforms:
  - version: PubNub JVM Chat SDK
    editors:
      - Java8+

