name: kmp-chat
version: 0.15.2
schema: 1
scm: github.com/pubnub/kmp-chat
sdks:
  - 
      type: library
      full-name: Kotlin Chat SDK
      short-name: Kotlin Chat
      artifacts:
        -
          language: kotlin
          tags:
            - Server
            - Mobile
          source-repository: https://github.com/pubnub/kmp-chat
          documentation: https://www.pubnub.com/docs/chat/kotlin-chat-sdk/overview
          tier: 2
          artifact-type: library
          distributions:
            -
              distribution-type: library
              distribution-repository: maven
              package-name: pubnub-chat-0.15.2
              location: https://repo.maven.apache.org/maven2/com/pubnub/pubnub-chat/0.15.2/
              supported-platforms:
                supported-operating-systems:
                  Android:
                    runtime-version:
                      - ART
                    target-api-level:
                      - 23
                    minimum-api-level:
                      - 23
                    maximum-api-level:
                      - 30
                    target-architecture:
                      - armeabi-v7a
                      - atom
                      - armeabi
                      - arm64-v8a
                  Linux:
                    runtime-version:
                      - JVM 8
                    minimum-os-version:
                      - Ubuntu 12.04
                    maximum-os-version:
                      - Ubuntu 20.04 LTS
                    target-architecture:
                      - x86
                      - x86-64
                  macOS:
                    runtime-version:
                      - JVM 8
                    minimum-os-version:
                      - macOS 10.12
                    maximum-os-version:
                      - macOS 11.0.1
                    target-architecture:
                      - x86-64
                  Windows:
                    runtime-version:
                      - JVM 8
                    minimum-os-version:
                      - Windows Vista Ultimate
                    maximum-os-version:
                      - Windows 10 Home
                    target-architecture:
                      - x86
                      - x86-64
              requires:
                -
                  name: pubnub-kotlin
                  min-version: 10.1.0
                  location: https://repo.maven.apache.org/maven2/com/pubnub/pubnub-kotlin/10.1.0/pubnub-kotlin-10.1.0.jar
                  license: PubNub Software Development Kit License
                  license-url: https://github.com/pubnub/kotlin/blob/master/LICENSE
                  is-required: Required
changelog:
  - date: 2025-08-07
    version: 0.15.2
    changes:
      - type: bug
        text: "Internal fixes."
  - date: 2025-07-31
    version: 0.15.1
    changes:
      - type: bug
        text: "Internal fixes."
  - date: 2025-07-31
    version: 0.15.0
    changes:
      - type: feature
        text: "AddConnectionStatusListener, reconnectSubscriptions, disconnectSubscriptions ."
  - date: 2025-07-30
    version: 0.14.1
    changes:
      - type: bug
        text: "Internal fixes."
  - date: 2025-07-21
    version: 0.14.0
    changes:
      - type: feature
        text: "Add support for channel groups."
  - date: 2025-06-10
    version: 0.13.4
    changes:
      - type: improvement
        text: "Internal fixes."
  - date: 2025-06-04
    version: 0.13.3
    changes:
      - type: bug
        text: "Adds an internal function workaround to get messages from an auto moderation report, which doesn't contain a message timetoken."
  - date: 2025-05-16
    version: 0.13.2
    changes:
      - type: bug
        text: "Internal fixes."
  - date: 2025-05-14
    version: 0.13.1
    changes:
      - type: bug
        text: "Internal fixes."
  - date: 2025-05-09
    version: 0.13.0
    changes:
      - type: feature
        text: "Add new API method returning paginated unread message counts."
  - date: 2025-03-21
    version: 0.12.1
    changes:
      - type: bug
        text: "Internal fixes."
  - date: 2025-03-14
    version: 0.12.0
    changes:
      - type: feature
        text: "Added possibility to invite users to public channels."
  - date: 2025-03-07
    version: 0.11.2
    changes:
      - type: bug
        text: "Update PubNub Kotlin SDK dependency to include proper handling of the device token."
      - type: bug
        text: "Add the missing keys when building the APNS payload."
  - date: 2025-02-20
    version: 0.11.1
    changes:
      - type: bug
        text: "Fixed bug related to setting user restriction. The issue occurred when `Enforce referential integrity for memberships` was enabled and a user did not exist in AppContext."
  - date: 2025-01-23
    version: 0.11.0
    changes:
      - type: feature
        text: "Added a new version of `User.update` that can be used to update data on the server without losing intermediate updates that might have happened in the time between when the object was last received and updated."
      - type: feature
        text: "Added the ability to mute and unmute users through `Chat.mutedUsers.muteUser() / unmuteUser()`."
      - type: feature
        text: "Added the option to automatically sync the mute list using App Context by enabling `ChatConfiguration.syncMutedUsers`."
      - type: feature
        text: "Added missing function to parse quoted message text into parts."
      - type: bug
        text: "Fixes the problem of overwriting custom data at regular intervals when `storeUserActivityInterval` is enabled."
  - date: 2025-01-13
    version: 0.10.1
    changes:
      - type: improvement
        text: "Internal fixes."
  - date: 2025-01-07
    version: 0.10.0
    changes:
      - type: feature
        text: "Added status and type to Membership."
  - date: 2024-12-20
    version: 0.9.4
    changes:
      - type: bug
        text: "Make setRestrictions work with `Enforce referential integrity for memberships` enabled on keyset."
  - date: 2024-12-16
    version: 0.9.3
    changes:
      - type: improvement
        text: "Internal fixes."
  - date: 2024-12-12
    version: v0.9.2
    changes:
      - type: feature
        text: "Lock moderated messages from editing ."
      - type: bug
        text: "Wrong user suggestion source for message draft created on ThreadChannel."
      - type: bug
        text: "Wrong type of last user activity time stored on server (precision)."
      - type: improvement
        text: "Moderation events are now sent to a channel prefixed with `PUBNUB_INTERNAL_MODERATION.`."
  - date: 2024-11-06
    version: v0.9.0
    changes:
      - type: feature
        text: "Added MessageDraft."
      - type: feature
        text: "Added timetoken utils methods."
      - type: bug
        text: "Added typingTimeoutMargin to improve continuity of typing indicator."
      - type: bug
        text: "Fix getTyping sending events after close."
      - type: bug
        text: "Change User.active() to synchronous val User.active."
      - type: bug
        text: "AccessManager is based on PAM V3 token instead of PAM V2 authKey."
      - type: bug
        text: "Hard delete returns null."
      - type: bug
        text: "Replace occurrences of Set with List where ordering matters."
  - date: 2024-09-24
    version: v0.8.0
    changes:
      - type: feature
        text: "Initial release of PubNub Kotlin Chat SDK."
  - date: 2024-06-26
    version: v0.8.0-DEV
    changes:
      - type: feature
        text: "Internal dev release."
supported-platforms:
  - version: PubNub Kotlin Chat SDK
    platforms:
      - Android 6.0 or higher
      - Linux (Ubuntu 12.04 or higher)
      - macOS 10.12 or higher
      - Windows Vista or higher
    editors:
      - Java8+
