name: kmp-chat
version: 0.8.0
schema: 1
scm: github.com/pubnub/kmp-chat
sdks:
  - 
      type: library
      full-name: Kotlin Chat SDK
      short-name: Chat
      artifacts:
        -
          language: kotlin
          tags:
            - Server
            - Mobile
          source-repository: https://github.com/pubnub/kmp-chat
          documentation: https://www.pubnub.com/docs/chat/kotlin-chat-sdk/overview
          tier: 2
          artifact-type: library
          distributions:
            -
              distribution-type: library
              distribution-repository: maven
              package-name: pubnub-chat-0.8.0
              location: https://repo.maven.apache.org/maven2/com/pubnub/pubnub-chat/0.8.0/
changelog:
  - date: 2024-09-24
    version: v0.8.0
    changes:
      - type: feature
        text: "Initial release of PubNub Kotlin Chat SDK."
  - date: 2024-06-26
    version: v0.8.0-DEV
    changes:
      - type: feature
        text: "Internal dev release."
supported-platforms:
  - version: PubNub Kotlin Chat SDK
    editors:
      - Java8+

