name: pubnub-js-chat
version: 0.13.0
scm: github.com/pubnub/js-chat
schema: 1
files:
  - lib/dist/index.js
supported-platforms:
  - version: "JavaScript Chat SDK"
    frameworks:
      - 'React'
      - 'React Native'
      - 'Vue'
      - 'Angular'
    platforms:
      - 'Chrome iOS 86.0.4240'
      - 'Chrome Android 86.0.4240'
      - 'Chrome Linux 86.0.4240'
      - 'Chrome macOS 86.0.4240'
      - 'Chrome Windows 86.0.4240'
      - 'Firefox Linux desktop 83.0 (x64)'
      - 'Firefox Linux desktop 83.0 (IA-32)'
      - 'Firefox iOS 29.0'
      - 'Firefox Windows 83.0 (IA-32)'
      - 'Firefox Windows 83.0 (x64)'
      - 'Firefox Windows 83.0 (ARM64)'
      - 'Firefox macOS 83.0'
      - 'Firefox Android 83.0 (x64)'
      - 'Firefox Android 83.0 (ARM64)'
      - 'Firefox Android 83.0 (IA-32 and ARMv7)'
      - 'Firefox OpenBSD 83.0 (IA-32,x64,ARM64)'
      - 'Microsoft Edge 87.0.664.60"'
      - 'Safari 13.0'
sdks:
  - type: library
    full-name: JavaScript Chat SDK
    short-name: Chat
    artifacts:
      - language: TypeScript
        tags:
          - Web
        source-repository: https://github.com/pubnub/kmp-chat
        documentation: https://www.pubnub.com/docs/chat/chat-sdk
        distributions:
          - distribution-type: library
            distribution-repository: GitHub release
            package-name: '@pubnub/chat'
            location: https://www.npmjs.com/package/@pubnub/chat/v/0.12.0
            requires:
              - name: 'pubnub'
                min-version: '8.6.0'
                license: 'MIT'
                license-url: 'https://github.com/pubnub/javascript/blob/master/LICENSE'
                location: 'Shipped within library'
                location-url: 'https://www.npmjs.com/package/pubnub'
                is-required: 'Required'
              - name: 'format-util'
                min-version: '1.0.5'
                license: 'MIT'
                license-url: 'https://github.com/tmpfs/format-util/blob/master/LICENSE'
                location: 'Shipped within library'
                location-url: 'https://www.npmjs.com/package/format-util'
                is-required: 'Required'
            supported-platforms:
              supported-browsers:
                minimun-supported-version:
                  - 'Chrome iOS 86.0.4240'
                  - 'Chrome Android 86.0.4240'
                  - 'Chrome Linux 86.0.4240'
                  - 'Chrome macOS 86.0.4240'
                  - 'Chrome Windows 86.0.4240'
                  - 'Firefox Linux desktop 83.0 (x64)'
                  - 'Firefox Linux desktop 83.0 (IA-32)'
                  - 'Firefox iOS 29.0'
                  - 'Firefox Windows 83.0 (IA-32)'
                  - 'Firefox Windows 83.0 (x64)'
                  - 'Firefox Windows 83.0 (ARM64)'
                  - 'Firefox macOS 83.0'
                  - 'Firefox Android 83.0 (x64)'
                  - 'Firefox Android 83.0 (ARM64)'
                  - 'Firefox Android 83.0 (IA-32 and ARMv7)'
                  - 'Firefox OpenBSD 83.0 (IA-32,x64,ARM64)'
                  - 'Microsoft Edge 87.0.664.60"'
                  - 'Safari 13.0'
changelog:
  - date: 2025-07-21
    version: 0.13.0
    changes:
      - type: feature
        text: "Add suport for channel groups."
  - date: 2025-06-04
    version: 0.12.1
    changes:
      - type: bug
        text: "Adds an internal function workaround to get messages from an auto moderation report, which doesn't contain a message timetoken."
  - date: 2025-05-09
    version: 0.12.0
    changes:
      - type: feature
        text: "Add possibility to invite users to public channels."
      - type: feature
        text: "Add new Chat method returning unread message counts with pagination tokens."
  - date: 2025-03-12
    version: 0.11.7
    changes:
      - type: bug
        text: "Add missing `version` and `auth_method` fields in APNS payload."
  - date: 2025-02-24
    version: 0.11.6
    changes:
      - type: bug
        text: "Fixed bug rel. to setRestriction. When 'Enforce referential integrity for memberships' is enabled then when setting restriction(channelMembers) we need to make sure that both channel and user exist in AppContext."
  - date: 2025-02-06
    version: 0.11.5
    changes:
      - type: bug
        text: "Fixed method sendEvent for event types different from custom ."
  - date: 2025-02-04
    version: 0.11.4
    changes:
      - type: bug
        text: "Added missing streamMessageReports method in JS."
  - date: 2025-01-30
    version: 0.11.3
    changes:
      - type: bug
        text: "When using the CustomPayloads configuration option in JS, allow the user to specify custom keys and preserve them when receiving messages."
  - date: 2025-01-30
    version: 0.11.2
    changes:
      - type: bug
        text: "Fixed input type in createConversation methods."
  - date: 2025-01-22
    version: 0.11.1
    changes:
      - type: bug
        text: "Add missing userId field in getUsersRestrictions result."
  - date: 2025-01-16
    version: 0.11.0
    changes:
      - type: improvement
        text: "The JS Chat SDK now uses TS types from recent versions of PubNub JS SDK instead of the ones in the `@types/pubnub` community resource. Changes to customer code might be required to accommodate this change."
  - date: 2025-01-08
    version: 0.10.0
    changes:
      - type: feature
        text: "Added status and type to Membership."
  - date: 2025-01-02
    version: 0.9.6
    changes:
      - type: bug
        text: "Channel type was erased (set to `null`) on edits to other Channel fields."
      - type: bug
        text: "Custom events sending/receiving in JS."
  - date: 2024-12-20
    version: 0.9.5
    changes:
      - type: bug
        text: "Make setRestrictions work with Enforce referential integrity for memberships enabled on keyset."
  - date: 2024-12-19
    version: 0.9.4
    changes:
      - type: bug
        text: "Crash when using `sort` parameter in various methods."
      - type: bug
        text: "GetChannels incorrectly returning an object with `users` property instead of `channels`."
  - date: 2024-12-12
    version: 0.9.2
    changes:
      - type: feature
        text: "MessageDraftV2 format to match other platforms Chat SDKs."
      - type: feature
        text: "Lock moderated messages from editing."
      - type: bug
        text: "Wrong user suggestion source for message draft created on ThreadChannel."
      - type: bug
        text: "Wrong type of last user activity time stored on server (precision)."
      - type: bug
        text: "Remove usage of `crypto` global (which required a polyfill)."
      - type: improvement
        text: "Moderation events are now sent to a channel prefixed with PUBNUB_INTERNAL_MODERATION."
  - date: 2024-12-07
    version: 0.9.1
    changes:
      - type: bug
        text: "Fix ES module named imports."
  - date: 2024-12-06
    version: 0.9.0-dev
    changes:
      - type: improvement
        text: "Internal code changes."
  - date: 2024-11-26
    version: v0.8.4
    changes:
      - type: feature
        text: "Lock messages from being edited."
      - type: feature
        text: "Remove reactions list if everyone removed them."
  - date: 2024-11-15
    version: v0.8.3
    changes:
      - type: feature
        text: "Add statusField for channel members."
  - date: 2024-08-27
    version: v0.8.2
    changes:
      - type: feature
        text: "Customize message reactions."
  - date: 2024-08-01
    version: v0.8.1
    changes:
      - type: feature
        text: "Bump JS SDK version to 8.2.7."
  - date: 2024-07-31
    version: v0.8.0
    changes:
      - type: feature
        text: "Message report events are now sent to a moderation sub-channel. Methods for user reporting and message reporting to a global admin channel are now deprecated and renamed with a DEPRECATED_ prefix."
  - date: 2024-06-18
    version: v0.7.3
    changes:
      - type: feature
        text: "Take membership related events while updating users into account ."
  - date: 2024-06-10
    version: v0.7.2
    changes:
      - type: feature
        text: "Respect eTag and updated fields in the Membership object."
  - date: 2024-06-05
    version: v0.7.1
    changes:
      - type: feature
        text: "Extend filter property for getMemberships."
  - date: 2024-05-22
    version: v0.7.0
    changes:
      - type: feature
        text: "Update JS SDK to 8.2.0."
      - type: feature
        text: "Remove look behind regexes for old Safari compatibility."
  - date: 2024-05-22
    version: v0.6.2
    changes:
      - type: bug
        text: "APNS environment was not set in push payloads."
  - date: 2024-05-21
    version: v0.6.1
    changes:
      - type: feature
        text: "Fix whose memberships are returned when using user.getMemberships()."
  - date: 2024-03-11
    version: v0.6.0
    changes:
      - type: feature
        text: "Check PAM permissions before sending signals."
      - type: feature
        text: "Allow custom payloads while sending and receiving messages."
  - date: 2024-01-16
    version: v0.5.2
    changes:
      - type: feature
        text: "Make ThreadMessage.streamUpdatesOn return ThreadMessage[] instead of Message[]."
  - date: 2023-12-18
    version: v0.5.1
    changes:
      - type: feature
        text: "Add missing reason parameter to user restrictions."
  - date: 2023-12-14
    version: v0.5.0
    changes:
      - type: feature
        text: "Add restore method to the Message entity."
      - type: feature
        text: "Add reason for user restrictions."
      - type: feature
        text: "Muted | banned | lifted)."
  - date: 2023-12-06
    version: v0.4.0
    changes:
      - type: feature
        text: "Add CryptoModule support."
  - date: 2023-11-08
    version: v0.3.1
    changes:
      - type: feature
        text: "Updated pubnub dependency to 7.4.3."
      - type: bug
        text: "Typo in moderation setRestrictions method names."
  - date: 2023-11-07
    version: v0.3.0
    changes:
      - type: feature
        text: "Updated pubnub dependency to 7.4.2."
      - type: feature
        text: "New type of software license."
      - type: feature
        text: "New `invite` custom event emitted when users are added to channels."
      - type: feature
        text: "Auto generation of channel IDs in every type of channel creation method, that can be bypassed."
      - type: feature
        text: "Fully optional parameters for `getUsers` and `getChannels` methods."
      - type: feature
        text: "Improved parameter lists for custom event related methods."
      - type: feature
        text: "Ability to forward message to the original channel."
      - type: bug
        text: "Behavior of spaces around mentions in Message Drafts."
  - date: 2023-10-23
    version: v0.2.0
    changes:
      - type: feature
        text: "Add moderation restriction methods."
      - type: feature
        text: "Change the way unread message count is calculated."
      - type: bug
        text: "Removing threads."
  - date: 2023-09-26
    version: v0.1.0
    changes:
      - type: feature
        text: "Initial release."
