# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Sample Chat app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample Chat app
  # pod "PubNubSwift", "~> 7"
  pod "pubnub_chat", :path => '../'
  pod "PubNubSwift", :path => '../pubnub-kotlin/swift'
end
