package com.pubnub.chat.config

import com.pubnub.api.enums.PNPushEnvironment
import com.pubnub.api.enums.PNPushType

/**
 * List of parameters you must set if you want to enable sending/receiving mobile push notifications for phone devices,
 * either through Apple Push Notification service (APNS) or Firebase Cloud Messaging (FCM).
 */
class PushNotificationsConfig(
    /**
     * The main option for enabling sending notifications. It must be set to true if you want a particular client
     * (whether a mobile device, web browser, or server) to send push notifications to mobile devices.
     *
     * These push notifications are messages with a provider-specific payload that the Chat SDK automatically attaches
     * to every message. Chat SDK includes a default payload setup for [deviceGateway] in every message sent to the
     * registered channels.
     *
     * This is the only required option to enable if you want to send push notifications to Android devices.
     * For iOS devices, you also have to configure [apnsTopic].
     */
    val sendPushes: Boolean,
    /**
     * Option for receiving notifications on iOS and Android devices.
     *
     * A device token refers to the unique identifier assigned to a specific mobile device by a platform's push
     * notification service. It targets and delivers push notifications to the intended app on that specific device.
     * Suppose you don't set this option and try to run channel registration-related methods. In that case, you'll
     * get the Device Token has to be defined in Chat pushNotifications config error.
     *
     * Refer to the official Apple and Google docs to learn how to obtain a device token for the APNs and FCM services.
     */
    val deviceToken: String?,
    /**
     * Option for receiving push notifications on Android (FCM) or iOS (APNS or APNS2) devices.
     * These are the available types:
     *
     * * APNS - Apple Push Notification service (legacy)
     * * APNS2 - Apple Push Notification service (new)
     * * FCM - Firebase Cloud Messaging (new)
     */
    val deviceGateway: PNPushType,
    /**
     * An Apple specific-option for sending and receiving notifications.
     *
     * This string is a bundle ID that you must define yourself for your iOS app so that Apple could enable push
     * notifications for it in APNs. The string takes the following format: com.domainname.applicationname.
     * Apple combines that ID with your Team ID (generated by Apple) and creates an App ID for your application.
     *
     * To send pushes from an iOS device, you must also set [sendPushes] to true. To receive pushes on an iOS device,
     * you must also set [deviceGateway] to [PNPushType.APNS2], define [deviceToken], and [apnsEnvironment].
     * Suppose you don't configure [apnsTopic], but set [deviceGateway] to `APNS2`.
     * In that case, you'll get the _apnsTopic has to be defined when deviceGateway is set to apns2_ error and Chat SDK
     * won't attach the APNS payload to messages.
     */
    val apnsTopic: String? = null,
    /**
     * Option for receiving notifications on iOS devices. When registering for push notifications, this option
     * specifies whether to use the development (`DEVELOPMENT`) or production (`PRODUCTION`) APNs environment.
     */
    val apnsEnvironment: PNPushEnvironment = PNPushEnvironment.DEVELOPMENT
)
