name: Validations

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  pubnub-yml:
    name: "Validate .pubnub.yml"
    runs-on:
      group: macos-gh
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout validator action
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: "Run '.pubnub.yml' file validation"
        uses: ./.github/.release/actions/actions/validators/pubnub-yml
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure