name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Integration and Unit tests
    runs-on:
      group: Default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build and run tests
        run: |
          ./gradlew check
        env:
          SDK_PUB_KEY: ${{ secrets.SDK_PUB_KEY }}
          SDK_SUB_KEY: ${{ secrets.SDK_PUB_KEY }}
          SDK_PAM_SUB_KEY: ${{ secrets.SDK_PAM_SUB_KEY }}
          SDK_PAM_PUB_KEY: ${{ secrets.SDK_PAM_PUB_KEY }}
          SDK_PAM_SEC_KEY: ${{ secrets.SDK_PAM_SEC_KEY }}
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure
  all-tests:
    name: Tests
    needs: [tests]
    runs-on:
      group: Default
    steps:
      - name: Tests summary
        run: echo -e "\033[38;2;95;215;0m\033[1mAll tests successfully passed"
